version: '2.9'

services:
  database:
    image: 'postgres'
    env_file:
     - ./back/.env
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - transcendence
  server:
    build:
      context: ./back
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - database
    volumes:
      - upload:/usr/src/app/uploads
    networks:
      - transcendence
  front:
    build:
      context: ./front
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    networks:
      - transcendence
  
networks:
  transcendence:

volumes:
  data:
  upload:
